"""empty message

Revision ID: 3be18890cd19
Revises: b3a9ee3c8e34
Create Date: 2017-09-30 08:50:52.508091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be18890cd19'
down_revision = 'b3a9ee3c8e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_details_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_details', ['user_details_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_details_id')
    # ### end Alembic commands ###
