"""empty message

Revision ID: b3a9ee3c8e34
Revises: e4e122ebc404
Create Date: 2017-09-30 08:39:08.729008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a9ee3c8e34'
down_revision = 'e4e122ebc404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    user_table = sa.sql.table('user',
                              sa.sql.column('id', sa.Integer),
                              sa.sql.column('email', sa.String),
                              sa.sql.column('password', sa.String),
                              sa.sql.column('active', sa.Boolean),
                              sa.sql.column('role_id', sa.Integer)
                              )
    op.bulk_insert(user_table,
                   [
                       {'id': 1,
                        'email': 'admin@maildrop.cc',
                        'password': '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
                        'active': True,
                        'role_id': 1}
                   ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###
